name: Github Actions Demo
run-name: ${{ github.actor }} is testing out Github Actions
on: 
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build-deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Print Trigger Namme
        run: echo "Trigger name ${{ github.event_name }}"

      - name: Checkout the Repository
        uses: actions/checkout@v7
        
      - name: List Repo Files
        run: ls

      - name: Build the app
        run: echo "Building the app"

      - name: Testing the app
        run: echo "Testing the app"

      - name: Build Docker Image
        run: echo "build the image."
    
      - name: Push to DockerHub
        run: echo "pushing the image to docker hub."

      - name: Deploy
        run: echo "Deploy the app on kubernetes."

        